'use client';
/* eslint-disable @next/next/no-html-link-for-pages */

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Check, ChevronDown, Clapperboard, FolderOpen, LayoutDashboard, Palette, Play, Save, Sparkles, Type } from 'lucide-react';
import '../studio.css';

type Settings = Record<string, string | number | boolean>;
type Template = { id?: string; name: string; settings: Settings };
const scenes = ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85'];
const initial: Template = { name: 'Meu modelo', settings: { aspectRatio: '9:16', layout: 'fill', captionPreset: 'Nix Pop', font: 'Arial', fontSize: 40, captionPosition: 'bottom', captionColor: '#ffffff', outlineColor: '#000000', captionOutline: 3, captionShadow: 1, uppercase: true, autoTitle: true, removeFiller: true, removePauses: false, highlightKeywords: true, aiEmoji: false, autoTransitions: true } };
const automation = [['autoTitle', 'Título automático'], ['removeFiller', 'Remover palavras de preenchimento'], ['removePauses', 'Remover pausas'], ['highlightKeywords', 'Destacar palavras-chave'], ['aiEmoji', 'Emojis nos momentos certos'], ['autoTransitions', 'Transições automáticas']] as const;

export default function TemplatesPage() {
  const [template, setTemplate] = useState<Template>(initial);
  const [saved, setSaved] = useState(false);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [error, setError] = useState('');
  const [scene, setScene] = useState(0);
  useEffect(() => { fetch('/api/templates').then((r) => r.ok ? r.json() : []).then(setTemplates).catch(() => undefined); }, []);
  const update = (key: string, value: string | number | boolean) => { setTemplate((current) => ({ ...current, settings: { ...current.settings, [key]: value } })); setSaved(false); };
  async function save() { setError(''); const response = await fetch('/api/templates', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(template) }); if (!response.ok) { setError('Não foi possível salvar o modelo. Confira se a migration foi aplicada.'); return; } const data = await response.json() as Template; setTemplate(data); setTemplates((current) => [data, ...current.filter((item) => item.id !== data.id)]); setSaved(true); }
  const settings = template.settings; const position = String(settings.captionPosition);
  const captionStyle = { fontFamily: String(settings.font), fontSize: `clamp(16px, ${Math.max(2, Number(settings.fontSize) / 9)}vw, 34px)`, color: String(settings.captionColor), WebkitTextStroke: `${Number(settings.captionOutline)}px ${String(settings.outlineColor)}`, textShadow: `0 ${Number(settings.captionShadow) * 2}px ${Number(settings.captionShadow) * 3}px rgba(0,0,0,.85)` };
  return <main className="studio-shell">
    <aside className="studio-sidebar template-sidebar"><a className="studio-brand" href="/"><span><Play size={12} fill="currentColor" /></span><strong>NixClip</strong></a><nav><a href="/studio" onClick={(event) => { event.preventDefault(); window.location.assign('/studio'); }}><LayoutDashboard size={18} /><span>Novo projeto</span></a><a href="/studio/projects" onClick={(event) => { event.preventDefault(); window.location.assign('/studio/projects'); }}><FolderOpen size={18} /><span>Projetos</span></a><a className="active" href="/studio/templates" onClick={(event) => { event.preventDefault(); window.location.assign('/studio/templates'); }}><Clapperboard size={18} /><span>Templates</span></a></nav></aside>
    <section className="studio-workspace project-detail"><header className="studio-header"><Link className="back-link" href="/studio">Studio</Link><div className="engine-status"><i /><span>Modelo de marca</span></div></header><div className="studio-content templates-page">
      <div className="project-detail-heading"><div><span className="step-label">IDENTIDADE</span><h1>Modelos de marca</h1><p>Defina uma vez o padrão visual e aplique em todos os cortes.</p></div><button className="generate-button" onClick={save}><Save size={16} /> {saved ? 'Modelo salvo' : 'Salvar modelo'}</button></div>
      {error && <div className="studio-error">{error}</div>}
      <div className="template-workbench"><div className="template-layout">
        <aside className="template-list"><h3>Seus modelos</h3>{templates.map((item) => <button key={item.id} className={item.id === template.id ? 'active' : ''} onClick={() => { setTemplate(item); setSaved(true); }}><span>{item.name}</span><ChevronDown size={14} /></button>)}<button className="new-template" onClick={() => { setTemplate({ ...initial, settings: { ...initial.settings } }); setSaved(false); }}>+ Novo modelo</button></aside>
        <section className="template-editor">
          <div className="template-section"><div className="template-section-title"><div><span>MODELO</span><h2>Nome e formato</h2></div><Palette size={18} /></div><label>Nome do modelo<input value={template.name} onChange={(e) => { setTemplate({ ...template, name: e.target.value }); setSaved(false); }} /></label><div className="option-grid">{['9:16', '1:1', '16:9', '4:5'].map((value) => <button className={settings.aspectRatio === value ? 'selected' : ''} onClick={() => update('aspectRatio', value)} key={value}>{value}</button>)}</div><div className="option-grid two">{['fill', 'fit'].map((value) => <button className={settings.layout === value ? 'selected' : ''} onClick={() => update('layout', value)} key={value}>{value === 'fill' ? 'Preencher' : 'Ajustar'}</button>)}</div></div>
          <div className="template-section"><div className="template-section-title"><div><span>LEGENDA</span><h2>Estilo das palavras</h2></div><Sparkles size={18} /></div><label>Preset<select value={String(settings.captionPreset)} onChange={(e) => update('captionPreset', e.target.value)}><option>Nix Pop</option><option>Impacto</option><option>Minimal</option><option>Karaokê</option></select></label><div className="field-row"><label>Fonte<input value={String(settings.font)} onChange={(e) => update('font', e.target.value)} /></label><label>Tamanho<input type="number" min="12" max="72" value={Number(settings.fontSize)} onChange={(e) => update('fontSize', Number(e.target.value))} /></label></div><div className="option-grid four">{[['top', 'Topo'], ['middle', 'Centro'], ['bottom', 'Base'], ['custom', 'Livre']].map(([value, label]) => <button className={settings.captionPosition === value ? 'selected' : ''} onClick={() => update('captionPosition', value)} key={value}>{label}</button>)}</div></div>
          <div className="template-section"><div className="template-section-title"><div><span>TIPOGRAFIA</span><h2>Cor e contraste</h2></div><Type size={18} /></div><div className="field-row colors"><label>Cor da legenda<input type="color" value={String(settings.captionColor)} onChange={(e) => update('captionColor', e.target.value)} /></label><label>Cor do contorno<input type="color" value={String(settings.outlineColor)} onChange={(e) => update('outlineColor', e.target.value)} /></label></div><div className="field-row"><label>Contorno<input type="number" min="0" max="12" value={Number(settings.captionOutline)} onChange={(e) => update('captionOutline', Number(e.target.value))} /></label><label>Sombra<input type="number" min="0" max="12" value={Number(settings.captionShadow)} onChange={(e) => update('captionShadow', Number(e.target.value))} /></label></div><label className="template-toggle"><span>Texto em maiúsculas</span><button className={settings.uppercase ? 'on' : ''} onClick={() => update('uppercase', !settings.uppercase)}><i /></button></label></div>
          <div className="template-section"><div className="template-section-title"><div><span>AUTOMAÇÃO</span><h2>Acabamento inteligente</h2></div><Check size={18} /></div>{automation.map(([key, label]) => <label className="template-toggle" key={key}><span>{label}</span><button className={settings[key] ? 'on' : ''} onClick={() => update(key, !settings[key])}><i /></button></label>)}</div>
        </section></div>
        <aside className="template-preview-panel"><div className="preview-panel-heading"><span>PRÉVIA AO VIVO</span><button onClick={() => setScene((current) => (current + 1) % scenes.length)}>Trocar cena</button></div><div className={`template-demo demo-${position}`} style={{ aspectRatio: String(settings.aspectRatio).replace(':', ' / '), backgroundImage: `url(${scenes[scene]})` }}><div className="demo-vignette" />{settings.autoTitle && <span className="demo-title">A IDEIA QUE MUDA TUDO</span>}<div className="demo-caption" style={captionStyle}>{settings.aiEmoji && <span>✨ </span>}{settings.uppercase ? 'VOCÊ NÃO PRECISA CRIAR MAIS' : 'Você não precisa criar mais'}</div><span className="demo-badge">DEMO · {settings.captionPreset}</span></div><p>Simulação visual. Ao gerar um projeto, as configurações escolhidas são enviadas ao conversor.</p></aside>
      </div>
    </div></section>
  </main>;
}
